//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/openstack-k8s-operators/lib-common/modules/common/condition"
	"github.com/openstack-k8s-operators/lib-common/modules/common/service"
	"github.com/openstack-k8s-operators/lib-common/modules/storage"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIOverrideSpec) DeepCopyInto(out *APIOverrideSpec) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = make(map[service.Endpoint]service.RoutedOverrideSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIOverrideSpec.
func (in *APIOverrideSpec) DeepCopy() *APIOverrideSpec {
	if in == nil {
		return nil
	}
	out := new(APIOverrideSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Designate) DeepCopyInto(out *Designate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Designate.
func (in *Designate) DeepCopy() *Designate {
	if in == nil {
		return nil
	}
	out := new(Designate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Designate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateAPI) DeepCopyInto(out *DesignateAPI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateAPI.
func (in *DesignateAPI) DeepCopy() *DesignateAPI {
	if in == nil {
		return nil
	}
	out := new(DesignateAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesignateAPI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateAPIList) DeepCopyInto(out *DesignateAPIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DesignateAPI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateAPIList.
func (in *DesignateAPIList) DeepCopy() *DesignateAPIList {
	if in == nil {
		return nil
	}
	out := new(DesignateAPIList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesignateAPIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateAPISpec) DeepCopyInto(out *DesignateAPISpec) {
	*out = *in
	in.DesignateAPISpecBase.DeepCopyInto(&out.DesignateAPISpecBase)
	in.DesignateServiceTemplate.DeepCopyInto(&out.DesignateServiceTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateAPISpec.
func (in *DesignateAPISpec) DeepCopy() *DesignateAPISpec {
	if in == nil {
		return nil
	}
	out := new(DesignateAPISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateAPISpecBase) DeepCopyInto(out *DesignateAPISpecBase) {
	*out = *in
	out.DesignateTemplate = in.DesignateTemplate
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Override.DeepCopyInto(&out.Override)
	in.TLS.DeepCopyInto(&out.TLS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateAPISpecBase.
func (in *DesignateAPISpecBase) DeepCopy() *DesignateAPISpecBase {
	if in == nil {
		return nil
	}
	out := new(DesignateAPISpecBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateAPISpecCore) DeepCopyInto(out *DesignateAPISpecCore) {
	*out = *in
	in.DesignateAPISpecBase.DeepCopyInto(&out.DesignateAPISpecBase)
	in.DesignateServiceTemplateCore.DeepCopyInto(&out.DesignateServiceTemplateCore)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateAPISpecCore.
func (in *DesignateAPISpecCore) DeepCopy() *DesignateAPISpecCore {
	if in == nil {
		return nil
	}
	out := new(DesignateAPISpecCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateAPIStatus) DeepCopyInto(out *DesignateAPIStatus) {
	*out = *in
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.APIEndpoints != nil {
		in, out := &in.APIEndpoints, &out.APIEndpoints
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetworkAttachments != nil {
		in, out := &in.NetworkAttachments, &out.NetworkAttachments
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateAPIStatus.
func (in *DesignateAPIStatus) DeepCopy() *DesignateAPIStatus {
	if in == nil {
		return nil
	}
	out := new(DesignateAPIStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateAPITemplate) DeepCopyInto(out *DesignateAPITemplate) {
	*out = *in
	in.DesignateServiceTemplate.DeepCopyInto(&out.DesignateServiceTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateAPITemplate.
func (in *DesignateAPITemplate) DeepCopy() *DesignateAPITemplate {
	if in == nil {
		return nil
	}
	out := new(DesignateAPITemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateBackendbind9) DeepCopyInto(out *DesignateBackendbind9) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateBackendbind9.
func (in *DesignateBackendbind9) DeepCopy() *DesignateBackendbind9 {
	if in == nil {
		return nil
	}
	out := new(DesignateBackendbind9)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesignateBackendbind9) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateBackendbind9List) DeepCopyInto(out *DesignateBackendbind9List) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DesignateBackendbind9, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateBackendbind9List.
func (in *DesignateBackendbind9List) DeepCopy() *DesignateBackendbind9List {
	if in == nil {
		return nil
	}
	out := new(DesignateBackendbind9List)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesignateBackendbind9List) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateBackendbind9Spec) DeepCopyInto(out *DesignateBackendbind9Spec) {
	*out = *in
	in.DesignateServiceTemplate.DeepCopyInto(&out.DesignateServiceTemplate)
	in.DesignateBackendbind9SpecBase.DeepCopyInto(&out.DesignateBackendbind9SpecBase)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateBackendbind9Spec.
func (in *DesignateBackendbind9Spec) DeepCopy() *DesignateBackendbind9Spec {
	if in == nil {
		return nil
	}
	out := new(DesignateBackendbind9Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateBackendbind9SpecBase) DeepCopyInto(out *DesignateBackendbind9SpecBase) {
	*out = *in
	out.DesignateTemplate = in.DesignateTemplate
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.CustomBindOptions != nil {
		in, out := &in.CustomBindOptions, &out.CustomBindOptions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateBackendbind9SpecBase.
func (in *DesignateBackendbind9SpecBase) DeepCopy() *DesignateBackendbind9SpecBase {
	if in == nil {
		return nil
	}
	out := new(DesignateBackendbind9SpecBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateBackendbind9SpecCore) DeepCopyInto(out *DesignateBackendbind9SpecCore) {
	*out = *in
	in.DesignateServiceTemplateCore.DeepCopyInto(&out.DesignateServiceTemplateCore)
	in.DesignateBackendbind9SpecBase.DeepCopyInto(&out.DesignateBackendbind9SpecBase)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateBackendbind9SpecCore.
func (in *DesignateBackendbind9SpecCore) DeepCopy() *DesignateBackendbind9SpecCore {
	if in == nil {
		return nil
	}
	out := new(DesignateBackendbind9SpecCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateBackendbind9Status) DeepCopyInto(out *DesignateBackendbind9Status) {
	*out = *in
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetworkAttachments != nil {
		in, out := &in.NetworkAttachments, &out.NetworkAttachments
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateBackendbind9Status.
func (in *DesignateBackendbind9Status) DeepCopy() *DesignateBackendbind9Status {
	if in == nil {
		return nil
	}
	out := new(DesignateBackendbind9Status)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateCentral) DeepCopyInto(out *DesignateCentral) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateCentral.
func (in *DesignateCentral) DeepCopy() *DesignateCentral {
	if in == nil {
		return nil
	}
	out := new(DesignateCentral)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesignateCentral) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateCentralList) DeepCopyInto(out *DesignateCentralList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DesignateCentral, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateCentralList.
func (in *DesignateCentralList) DeepCopy() *DesignateCentralList {
	if in == nil {
		return nil
	}
	out := new(DesignateCentralList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesignateCentralList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateCentralSpec) DeepCopyInto(out *DesignateCentralSpec) {
	*out = *in
	in.DesignateServiceTemplate.DeepCopyInto(&out.DesignateServiceTemplate)
	in.DesignateCentralSpecBase.DeepCopyInto(&out.DesignateCentralSpecBase)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateCentralSpec.
func (in *DesignateCentralSpec) DeepCopy() *DesignateCentralSpec {
	if in == nil {
		return nil
	}
	out := new(DesignateCentralSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateCentralSpecBase) DeepCopyInto(out *DesignateCentralSpecBase) {
	*out = *in
	out.DesignateTemplate = in.DesignateTemplate
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	out.TLS = in.TLS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateCentralSpecBase.
func (in *DesignateCentralSpecBase) DeepCopy() *DesignateCentralSpecBase {
	if in == nil {
		return nil
	}
	out := new(DesignateCentralSpecBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateCentralSpecCore) DeepCopyInto(out *DesignateCentralSpecCore) {
	*out = *in
	in.DesignateServiceTemplateCore.DeepCopyInto(&out.DesignateServiceTemplateCore)
	in.DesignateCentralSpecBase.DeepCopyInto(&out.DesignateCentralSpecBase)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateCentralSpecCore.
func (in *DesignateCentralSpecCore) DeepCopy() *DesignateCentralSpecCore {
	if in == nil {
		return nil
	}
	out := new(DesignateCentralSpecCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateCentralStatus) DeepCopyInto(out *DesignateCentralStatus) {
	*out = *in
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetworkAttachments != nil {
		in, out := &in.NetworkAttachments, &out.NetworkAttachments
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateCentralStatus.
func (in *DesignateCentralStatus) DeepCopy() *DesignateCentralStatus {
	if in == nil {
		return nil
	}
	out := new(DesignateCentralStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateDefaults) DeepCopyInto(out *DesignateDefaults) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateDefaults.
func (in *DesignateDefaults) DeepCopy() *DesignateDefaults {
	if in == nil {
		return nil
	}
	out := new(DesignateDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateExtraVolMounts) DeepCopyInto(out *DesignateExtraVolMounts) {
	*out = *in
	if in.VolMounts != nil {
		in, out := &in.VolMounts, &out.VolMounts
		*out = make([]storage.VolMounts, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateExtraVolMounts.
func (in *DesignateExtraVolMounts) DeepCopy() *DesignateExtraVolMounts {
	if in == nil {
		return nil
	}
	out := new(DesignateExtraVolMounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateList) DeepCopyInto(out *DesignateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Designate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateList.
func (in *DesignateList) DeepCopy() *DesignateList {
	if in == nil {
		return nil
	}
	out := new(DesignateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesignateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateMdns) DeepCopyInto(out *DesignateMdns) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateMdns.
func (in *DesignateMdns) DeepCopy() *DesignateMdns {
	if in == nil {
		return nil
	}
	out := new(DesignateMdns)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesignateMdns) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateMdnsList) DeepCopyInto(out *DesignateMdnsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DesignateMdns, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateMdnsList.
func (in *DesignateMdnsList) DeepCopy() *DesignateMdnsList {
	if in == nil {
		return nil
	}
	out := new(DesignateMdnsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesignateMdnsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateMdnsSpec) DeepCopyInto(out *DesignateMdnsSpec) {
	*out = *in
	in.DesignateServiceTemplate.DeepCopyInto(&out.DesignateServiceTemplate)
	out.DesignateMdnsSpecBase = in.DesignateMdnsSpecBase
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateMdnsSpec.
func (in *DesignateMdnsSpec) DeepCopy() *DesignateMdnsSpec {
	if in == nil {
		return nil
	}
	out := new(DesignateMdnsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateMdnsSpecBase) DeepCopyInto(out *DesignateMdnsSpecBase) {
	*out = *in
	out.DesignateTemplate = in.DesignateTemplate
	out.TLS = in.TLS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateMdnsSpecBase.
func (in *DesignateMdnsSpecBase) DeepCopy() *DesignateMdnsSpecBase {
	if in == nil {
		return nil
	}
	out := new(DesignateMdnsSpecBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateMdnsSpecCore) DeepCopyInto(out *DesignateMdnsSpecCore) {
	*out = *in
	in.DesignateServiceTemplateCore.DeepCopyInto(&out.DesignateServiceTemplateCore)
	out.DesignateMdnsSpecBase = in.DesignateMdnsSpecBase
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateMdnsSpecCore.
func (in *DesignateMdnsSpecCore) DeepCopy() *DesignateMdnsSpecCore {
	if in == nil {
		return nil
	}
	out := new(DesignateMdnsSpecCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateMdnsStatus) DeepCopyInto(out *DesignateMdnsStatus) {
	*out = *in
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetworkAttachments != nil {
		in, out := &in.NetworkAttachments, &out.NetworkAttachments
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateMdnsStatus.
func (in *DesignateMdnsStatus) DeepCopy() *DesignateMdnsStatus {
	if in == nil {
		return nil
	}
	out := new(DesignateMdnsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateProducer) DeepCopyInto(out *DesignateProducer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateProducer.
func (in *DesignateProducer) DeepCopy() *DesignateProducer {
	if in == nil {
		return nil
	}
	out := new(DesignateProducer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesignateProducer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateProducerList) DeepCopyInto(out *DesignateProducerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DesignateProducer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateProducerList.
func (in *DesignateProducerList) DeepCopy() *DesignateProducerList {
	if in == nil {
		return nil
	}
	out := new(DesignateProducerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesignateProducerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateProducerSpec) DeepCopyInto(out *DesignateProducerSpec) {
	*out = *in
	in.DesignateServiceTemplate.DeepCopyInto(&out.DesignateServiceTemplate)
	in.DesignateProducerSpecBase.DeepCopyInto(&out.DesignateProducerSpecBase)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateProducerSpec.
func (in *DesignateProducerSpec) DeepCopy() *DesignateProducerSpec {
	if in == nil {
		return nil
	}
	out := new(DesignateProducerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateProducerSpecBase) DeepCopyInto(out *DesignateProducerSpecBase) {
	*out = *in
	out.DesignateTemplate = in.DesignateTemplate
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	out.TLS = in.TLS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateProducerSpecBase.
func (in *DesignateProducerSpecBase) DeepCopy() *DesignateProducerSpecBase {
	if in == nil {
		return nil
	}
	out := new(DesignateProducerSpecBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateProducerSpecCore) DeepCopyInto(out *DesignateProducerSpecCore) {
	*out = *in
	in.DesignateServiceTemplateCore.DeepCopyInto(&out.DesignateServiceTemplateCore)
	in.DesignateProducerSpecBase.DeepCopyInto(&out.DesignateProducerSpecBase)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateProducerSpecCore.
func (in *DesignateProducerSpecCore) DeepCopy() *DesignateProducerSpecCore {
	if in == nil {
		return nil
	}
	out := new(DesignateProducerSpecCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateProducerStatus) DeepCopyInto(out *DesignateProducerStatus) {
	*out = *in
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetworkAttachments != nil {
		in, out := &in.NetworkAttachments, &out.NetworkAttachments
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateProducerStatus.
func (in *DesignateProducerStatus) DeepCopy() *DesignateProducerStatus {
	if in == nil {
		return nil
	}
	out := new(DesignateProducerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateServiceTemplate) DeepCopyInto(out *DesignateServiceTemplate) {
	*out = *in
	in.DesignateServiceTemplateCore.DeepCopyInto(&out.DesignateServiceTemplateCore)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateServiceTemplate.
func (in *DesignateServiceTemplate) DeepCopy() *DesignateServiceTemplate {
	if in == nil {
		return nil
	}
	out := new(DesignateServiceTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateServiceTemplateCore) DeepCopyInto(out *DesignateServiceTemplateCore) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CustomServiceConfigSecrets != nil {
		in, out := &in.CustomServiceConfigSecrets, &out.CustomServiceConfigSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultConfigOverwrite != nil {
		in, out := &in.DefaultConfigOverwrite, &out.DefaultConfigOverwrite
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NetworkAttachments != nil {
		in, out := &in.NetworkAttachments, &out.NetworkAttachments
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateServiceTemplateCore.
func (in *DesignateServiceTemplateCore) DeepCopy() *DesignateServiceTemplateCore {
	if in == nil {
		return nil
	}
	out := new(DesignateServiceTemplateCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateSpec) DeepCopyInto(out *DesignateSpec) {
	*out = *in
	in.DesignateSpecBase.DeepCopyInto(&out.DesignateSpecBase)
	in.DesignateAPI.DeepCopyInto(&out.DesignateAPI)
	in.DesignateCentral.DeepCopyInto(&out.DesignateCentral)
	in.DesignateWorker.DeepCopyInto(&out.DesignateWorker)
	in.DesignateMdns.DeepCopyInto(&out.DesignateMdns)
	in.DesignateProducer.DeepCopyInto(&out.DesignateProducer)
	in.DesignateBackendbind9.DeepCopyInto(&out.DesignateBackendbind9)
	in.DesignateUnbound.DeepCopyInto(&out.DesignateUnbound)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateSpec.
func (in *DesignateSpec) DeepCopy() *DesignateSpec {
	if in == nil {
		return nil
	}
	out := new(DesignateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateSpecBase) DeepCopyInto(out *DesignateSpecBase) {
	*out = *in
	out.PasswordSelectors = in.PasswordSelectors
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefaultConfigOverwrite != nil {
		in, out := &in.DefaultConfigOverwrite, &out.DefaultConfigOverwrite
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateSpecBase.
func (in *DesignateSpecBase) DeepCopy() *DesignateSpecBase {
	if in == nil {
		return nil
	}
	out := new(DesignateSpecBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateSpecCore) DeepCopyInto(out *DesignateSpecCore) {
	*out = *in
	in.DesignateSpecBase.DeepCopyInto(&out.DesignateSpecBase)
	in.DesignateAPI.DeepCopyInto(&out.DesignateAPI)
	in.DesignateCentral.DeepCopyInto(&out.DesignateCentral)
	in.DesignateWorker.DeepCopyInto(&out.DesignateWorker)
	in.DesignateMdns.DeepCopyInto(&out.DesignateMdns)
	in.DesignateProducer.DeepCopyInto(&out.DesignateProducer)
	in.DesignateBackendbind9.DeepCopyInto(&out.DesignateBackendbind9)
	in.DesignateUnbound.DeepCopyInto(&out.DesignateUnbound)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateSpecCore.
func (in *DesignateSpecCore) DeepCopy() *DesignateSpecCore {
	if in == nil {
		return nil
	}
	out := new(DesignateSpecCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateStatus) DeepCopyInto(out *DesignateStatus) {
	*out = *in
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.APIEndpoints != nil {
		in, out := &in.APIEndpoints, &out.APIEndpoints
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateStatus.
func (in *DesignateStatus) DeepCopy() *DesignateStatus {
	if in == nil {
		return nil
	}
	out := new(DesignateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateTemplate) DeepCopyInto(out *DesignateTemplate) {
	*out = *in
	out.PasswordSelectors = in.PasswordSelectors
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateTemplate.
func (in *DesignateTemplate) DeepCopy() *DesignateTemplate {
	if in == nil {
		return nil
	}
	out := new(DesignateTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateUnbound) DeepCopyInto(out *DesignateUnbound) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateUnbound.
func (in *DesignateUnbound) DeepCopy() *DesignateUnbound {
	if in == nil {
		return nil
	}
	out := new(DesignateUnbound)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesignateUnbound) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateUnboundList) DeepCopyInto(out *DesignateUnboundList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DesignateUnbound, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateUnboundList.
func (in *DesignateUnboundList) DeepCopy() *DesignateUnboundList {
	if in == nil {
		return nil
	}
	out := new(DesignateUnboundList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesignateUnboundList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateUnboundSpec) DeepCopyInto(out *DesignateUnboundSpec) {
	*out = *in
	in.DesignateServiceTemplate.DeepCopyInto(&out.DesignateServiceTemplate)
	in.DesignateUnboundSpecBase.DeepCopyInto(&out.DesignateUnboundSpecBase)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateUnboundSpec.
func (in *DesignateUnboundSpec) DeepCopy() *DesignateUnboundSpec {
	if in == nil {
		return nil
	}
	out := new(DesignateUnboundSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateUnboundSpecBase) DeepCopyInto(out *DesignateUnboundSpecBase) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateUnboundSpecBase.
func (in *DesignateUnboundSpecBase) DeepCopy() *DesignateUnboundSpecBase {
	if in == nil {
		return nil
	}
	out := new(DesignateUnboundSpecBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateUnboundSpecCore) DeepCopyInto(out *DesignateUnboundSpecCore) {
	*out = *in
	in.DesignateServiceTemplateCore.DeepCopyInto(&out.DesignateServiceTemplateCore)
	in.DesignateUnboundSpecBase.DeepCopyInto(&out.DesignateUnboundSpecBase)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateUnboundSpecCore.
func (in *DesignateUnboundSpecCore) DeepCopy() *DesignateUnboundSpecCore {
	if in == nil {
		return nil
	}
	out := new(DesignateUnboundSpecCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateUnboundStatus) DeepCopyInto(out *DesignateUnboundStatus) {
	*out = *in
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetworkAttachments != nil {
		in, out := &in.NetworkAttachments, &out.NetworkAttachments
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateUnboundStatus.
func (in *DesignateUnboundStatus) DeepCopy() *DesignateUnboundStatus {
	if in == nil {
		return nil
	}
	out := new(DesignateUnboundStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateWorker) DeepCopyInto(out *DesignateWorker) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateWorker.
func (in *DesignateWorker) DeepCopy() *DesignateWorker {
	if in == nil {
		return nil
	}
	out := new(DesignateWorker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesignateWorker) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateWorkerList) DeepCopyInto(out *DesignateWorkerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DesignateWorker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateWorkerList.
func (in *DesignateWorkerList) DeepCopy() *DesignateWorkerList {
	if in == nil {
		return nil
	}
	out := new(DesignateWorkerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesignateWorkerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateWorkerSpec) DeepCopyInto(out *DesignateWorkerSpec) {
	*out = *in
	in.DesignateServiceTemplate.DeepCopyInto(&out.DesignateServiceTemplate)
	in.DesignateWorkerSpecBase.DeepCopyInto(&out.DesignateWorkerSpecBase)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateWorkerSpec.
func (in *DesignateWorkerSpec) DeepCopy() *DesignateWorkerSpec {
	if in == nil {
		return nil
	}
	out := new(DesignateWorkerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateWorkerSpecBase) DeepCopyInto(out *DesignateWorkerSpecBase) {
	*out = *in
	out.DesignateTemplate = in.DesignateTemplate
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	out.TLS = in.TLS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateWorkerSpecBase.
func (in *DesignateWorkerSpecBase) DeepCopy() *DesignateWorkerSpecBase {
	if in == nil {
		return nil
	}
	out := new(DesignateWorkerSpecBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateWorkerSpecCore) DeepCopyInto(out *DesignateWorkerSpecCore) {
	*out = *in
	in.DesignateServiceTemplateCore.DeepCopyInto(&out.DesignateServiceTemplateCore)
	in.DesignateWorkerSpecBase.DeepCopyInto(&out.DesignateWorkerSpecBase)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateWorkerSpecCore.
func (in *DesignateWorkerSpecCore) DeepCopy() *DesignateWorkerSpecCore {
	if in == nil {
		return nil
	}
	out := new(DesignateWorkerSpecCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesignateWorkerStatus) DeepCopyInto(out *DesignateWorkerStatus) {
	*out = *in
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetworkAttachments != nil {
		in, out := &in.NetworkAttachments, &out.NetworkAttachments
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesignateWorkerStatus.
func (in *DesignateWorkerStatus) DeepCopy() *DesignateWorkerStatus {
	if in == nil {
		return nil
	}
	out := new(DesignateWorkerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PasswordSelector) DeepCopyInto(out *PasswordSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PasswordSelector.
func (in *PasswordSelector) DeepCopy() *PasswordSelector {
	if in == nil {
		return nil
	}
	out := new(PasswordSelector)
	in.DeepCopyInto(out)
	return out
}
